---
modelFingerprint: "245512C21E6B92DF828AE3190F944F6E"
methods:
- method:
    name: "stream"
    returnType: "java.util.stream.Stream"
    signature: "stream() : java.util.stream.Stream<org.springframework.boot.context.properties.source.ConfigurationPropertyName>"
    instructionFingerprint: "874FCD71A0A981E2FFB5277947E0B482"
    parametersTypes: []
  paths:
  - pathId: "path1"
    pathIdForUser: "path1"
    testPathName: "streamTest"
    nameDefinedByUser: false
    constructorSignature: "<init>(org.springframework.boot.context.properties.source.IterableConfigurationPropertySource,org.springframework.boot.context.properties.source.ConfigurationPropertyNameAliases)\
      \ : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "16881175CEC81517D592ACDFA082E5C9"
    problemWasSolvedByProver: false
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "CE09A2D36160389B05B7F39FFA8E4565"
      index: 1
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "OBJECT"
        content: !<new>
          target: "org.springframework.boot.context.properties.source.AliasedIterableConfigurationPropertySource"
          parameters:
          - name: "source"
            value:
              sapientType: "MOCK"
              valueType: "org.springframework.boot.context.properties.source.IterableConfigurationPropertySource"
              uuid: "<init>_iterableConfigurationPropertySource1"
              fixed: false
              equalsMethodPresent: false
              explicitCastNeeded: false
          - name: "aliases"
            value:
              sapientType: "MOCK"
              valueType: "org.springframework.boot.context.properties.source.ConfigurationPropertyNameAliases"
              uuid: "<init>_configurationPropertyNameAliases1"
              fixed: false
              equalsMethodPresent: false
              explicitCastNeeded: false
          privateConstructor: false
          createdByTargetCode: false
        suggestedContent: !<new>
          target: "org.springframework.boot.context.properties.source.AliasedIterableConfigurationPropertySource"
          parameters:
          - name: "source"
            value:
              sapientType: "UNKNOWN"
              valueType: "org.springframework.boot.context.properties.source.IterableConfigurationPropertySource"
              uuid: "<init>_iterableConfigurationPropertySource1"
              fixed: false
              equalsMethodPresent: false
              explicitCastNeeded: false
          - name: "aliases"
            value:
              sapientType: "UNKNOWN"
              valueType: "org.springframework.boot.context.properties.source.ConfigurationPropertyNameAliases"
              uuid: "<init>_configurationPropertyNameAliases1"
              fixed: false
              equalsMethodPresent: false
              explicitCastNeeded: false
          privateConstructor: false
          createdByTargetCode: false
        valueType: "org.springframework.boot.context.properties.source.AliasedIterableConfigurationPropertySource"
        uuid: "target"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "Assert"
      modelFingerprint: "3BCF9F71C3464BC4B8DD432AD321B6D9"
      index: 2
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        valueType: "org.springframework.util.Assert"
        uuid: "org.springframework.util.Assert"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "org.springframework.util.Assert"
        name: "notNull"
        parameters:
        - name: "object"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.boot.context.properties.source.IterableConfigurationPropertySource"
            uuid: "<init>_iterableConfigurationPropertySource1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "message"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "Source must not be null"
            valueType: "java.lang.String"
            fixed: true
            equalsMethodPresent: false
            explicitCastNeeded: false
        signature: "notNull(IterableConfigurationPropertySource,String): void"
        returnValue:
          sapientType: "VOID"
          valueType: "void"
          uuid: "<init>_void1"
          fixed: true
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "Assert"
      modelFingerprint: "200466189AD84BFA7EAA32C91B2F6C8A"
      index: 3
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        valueType: "org.springframework.util.Assert"
        uuid: "org.springframework.util.Assert"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "org.springframework.util.Assert"
        name: "notNull"
        parameters:
        - name: "object"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.boot.context.properties.source.ConfigurationPropertyNameAliases"
            uuid: "<init>_configurationPropertyNameAliases1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "message"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "Aliases must not be null"
            valueType: "java.lang.String"
            fixed: true
            equalsMethodPresent: false
            explicitCastNeeded: false
        signature: "notNull(ConfigurationPropertyNameAliases,String): void"
        returnValue:
          sapientType: "VOID"
          valueType: "void"
          uuid: "<init>_void2"
          fixed: true
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "INTERNAL"
      name: "internalMethod"
      modelFingerprint: "ABD3BA9BDB07FBA37DB2E6C185F38490"
      index: 4
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      methodExercised:
        target: "target"
        name: "getSource"
        parameters: []
        signature: "getSource(): IterableConfigurationPropertySource"
        returnValue:
          sapientType: "MOCK"
          valueType: "org.springframework.boot.context.properties.source.IterableConfigurationPropertySource"
          uuid: "stream_iterableConfigurationPropertySource1"
          fixed: false
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 4
      staticReadMethodForField: false
      filledByUser: false
    - type: "LOCAL_VARIABLE"
      modelFingerprint: "F6F308D2A4A43F315058DFB56F570F64"
      index: 5
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        valueType: "org.springframework.boot.context.properties.source.IterableConfigurationPropertySource"
        uuid: "stream_iterableConfigurationPropertySource1"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "org.springframework.boot.context.properties.source.IterableConfigurationPropertySource"
        name: "stream"
        parameters: []
        signature: "stream(): Stream"
        returnValue:
          sapientType: "OBJECT"
          content: !<static_method_return>
            target: "java.util.stream.Stream"
            method: "empty"
            methodParameters: []
          suggestedContent: !<static_method_return>
            target: "java.util.stream.Stream"
            method: "empty"
            methodParameters: []
          valueType: "java.util.stream.Stream"
          uuid: "stream_stream1"
          fixed: false
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 1025
      staticReadMethodForField: false
      filledByUser: false
    - type: "RESULT"
      name: "result"
      modelFingerprint: "C753BC527FB9F94CD92387C5F4B57BA4"
      index: 6
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "OBJECT"
        content: !<static_method_return>
          target: "java.util.stream.Stream"
          method: "empty"
          methodParameters: []
        suggestedContent: !<static_method_return>
          target: "java.util.stream.Stream"
          method: "empty"
          methodParameters: []
        valueType: "java.util.stream.Stream"
        uuid: "stream_stream2"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    uuid: "b4af2388-e781-3800-820a-b8ede09bd914"
    deleted: false
    disabled: false
    ignoredBySystem: false
    failureReason:
      reason: "METHOD_WITHOUT_EXPRESSION_SUPPORT"
      details: "Expression missing: java.util.stream.Stream.flatMap(java.util.function.Function)\
        \ : java.util.stream.Stream<org.springframework.boot.context.properties.source.ConfigurationPropertyName>"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
- method:
    name: "getSource"
    returnType: "org.springframework.boot.context.properties.source.IterableConfigurationPropertySource"
    signature: "getSource() : org.springframework.boot.context.properties.source.IterableConfigurationPropertySource"
    instructionFingerprint: "3EC400BDAF5814B52DCD3AD800B2BE43"
    parametersTypes: []
  paths:
  - pathId: "path1"
    pathIdForUser: "path1"
    testPathName: "getSource1Test"
    nameDefinedByUser: false
    constructorSignature: "<init>(org.springframework.boot.context.properties.source.IterableConfigurationPropertySource,org.springframework.boot.context.properties.source.ConfigurationPropertyNameAliases)\
      \ : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "A17C129C6912D4283650524DA9998126"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "CE09A2D36160389B05B7F39FFA8E4565"
      index: 1
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "OBJECT"
        content: !<new>
          target: "org.springframework.boot.context.properties.source.AliasedIterableConfigurationPropertySource"
          parameters:
          - name: "source"
            value:
              sapientType: "MOCK"
              valueType: "org.springframework.boot.context.properties.source.IterableConfigurationPropertySource"
              uuid: "<init>_iterableConfigurationPropertySource1"
              fixed: false
              equalsMethodPresent: false
              explicitCastNeeded: false
          - name: "aliases"
            value:
              sapientType: "MOCK"
              valueType: "org.springframework.boot.context.properties.source.ConfigurationPropertyNameAliases"
              uuid: "<init>_configurationPropertyNameAliases1"
              fixed: false
              equalsMethodPresent: false
              explicitCastNeeded: false
          privateConstructor: false
          createdByTargetCode: false
        suggestedContent: !<new>
          target: "org.springframework.boot.context.properties.source.AliasedIterableConfigurationPropertySource"
          parameters:
          - name: "source"
            value:
              sapientType: "UNKNOWN"
              valueType: "org.springframework.boot.context.properties.source.IterableConfigurationPropertySource"
              uuid: "<init>_iterableConfigurationPropertySource1"
              fixed: false
              equalsMethodPresent: false
              explicitCastNeeded: false
          - name: "aliases"
            value:
              sapientType: "UNKNOWN"
              valueType: "org.springframework.boot.context.properties.source.ConfigurationPropertyNameAliases"
              uuid: "<init>_configurationPropertyNameAliases1"
              fixed: false
              equalsMethodPresent: false
              explicitCastNeeded: false
          privateConstructor: false
          createdByTargetCode: false
        valueType: "org.springframework.boot.context.properties.source.AliasedIterableConfigurationPropertySource"
        uuid: "target"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "Assert"
      modelFingerprint: "3BCF9F71C3464BC4B8DD432AD321B6D9"
      index: 2
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        valueType: "org.springframework.util.Assert"
        uuid: "org.springframework.util.Assert"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "org.springframework.util.Assert"
        name: "notNull"
        parameters:
        - name: "object"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.boot.context.properties.source.IterableConfigurationPropertySource"
            uuid: "<init>_iterableConfigurationPropertySource1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "message"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "Source must not be null"
            valueType: "java.lang.String"
            fixed: true
            equalsMethodPresent: false
            explicitCastNeeded: false
        signature: "notNull(IterableConfigurationPropertySource,String): void"
        returnValue:
          sapientType: "VOID"
          valueType: "void"
          uuid: "<init>_void1"
          fixed: true
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "Assert"
      modelFingerprint: "200466189AD84BFA7EAA32C91B2F6C8A"
      index: 3
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        valueType: "org.springframework.util.Assert"
        uuid: "org.springframework.util.Assert"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "org.springframework.util.Assert"
        name: "notNull"
        parameters:
        - name: "object"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.boot.context.properties.source.ConfigurationPropertyNameAliases"
            uuid: "<init>_configurationPropertyNameAliases1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "message"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "Aliases must not be null"
            valueType: "java.lang.String"
            fixed: true
            equalsMethodPresent: false
            explicitCastNeeded: false
        signature: "notNull(ConfigurationPropertyNameAliases,String): void"
        returnValue:
          sapientType: "VOID"
          valueType: "void"
          uuid: "<init>_void2"
          fixed: true
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "RESULT"
      name: "result"
      modelFingerprint: "B858CC7ADF4138B2495DFF7300E5B929"
      index: 4
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        valueType: "org.springframework.boot.context.properties.source.IterableConfigurationPropertySource"
        uuid: "<init>_iterableConfigurationPropertySource1"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    uuid: "bfcb6725-5fb8-3080-8655-dc87e9921af1"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
