---
modelFingerprint: "861E503AC646F76A182D5C0340460BEC"
methods:
- method:
    name: "search"
    returnType: "org.springframework.boot.context.properties.source.ConfigurationPropertyState"
    signature: "search(java.lang.Iterable<java.lang.Object>,java.util.function.Predicate<java.lang.Object>)\
      \ : org.springframework.boot.context.properties.source.ConfigurationPropertyState"
    instructionFingerprint: "15BE33C472B9C4B7425E811BA42FE78F"
    parametersTypes:
    - "java.lang.Iterable"
    - "java.util.function.Predicate"
  paths:
  - pathId: "path1"
    pathIdForUser: "path1"
    testPathName: "searchWhenPredicateTestItem"
    nameDefinedByUser: false
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "E5240A2160FDBD2589700B2EC7FB1394"
    problemWasSolvedByProver: false
    truncated: false
    inputParameters:
    - type: "INPUT"
      name: "source"
      modelFingerprint: "5BFEDCB7460AC592DAB3A8DD97CED8A8"
      index: 1
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        valueType: "java.lang.Iterable"
        uuid: "search_iterable1"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "INPUT"
      name: "predicate"
      modelFingerprint: "5AB160B1932BFCC24800D287A98C368D"
      index: 2
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        valueType: "java.util.function.Predicate"
        uuid: "search_predicate1"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "Assert"
      modelFingerprint: "D66D5F9FFE63C8E4B829FE6D193CE6E1"
      index: 3
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        valueType: "org.springframework.util.Assert"
        uuid: "org.springframework.util.Assert"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "org.springframework.util.Assert"
        name: "notNull"
        parameters:
        - name: "object"
          value:
            sapientType: "MOCK"
            valueType: "java.lang.Iterable"
            uuid: "search_iterable1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "message"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "Source must not be null"
            valueType: "java.lang.String"
            fixed: true
            equalsMethodPresent: false
            explicitCastNeeded: false
        signature: "notNull(Iterable,String): void"
        returnValue:
          sapientType: "VOID"
          valueType: "void"
          uuid: "search_void1"
          fixed: true
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "Assert"
      modelFingerprint: "55779EEE47C46E4306B2E65D8107E32A"
      index: 4
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        valueType: "org.springframework.util.Assert"
        uuid: "org.springframework.util.Assert"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "org.springframework.util.Assert"
        name: "notNull"
        parameters:
        - name: "object"
          value:
            sapientType: "MOCK"
            valueType: "java.util.function.Predicate"
            uuid: "search_predicate1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "message"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "Predicate must not be null"
            valueType: "java.lang.String"
            fixed: true
            equalsMethodPresent: false
            explicitCastNeeded: false
        signature: "notNull(Predicate,String): void"
        returnValue:
          sapientType: "VOID"
          valueType: "void"
          uuid: "search_void2"
          fixed: true
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "RESULT"
      name: "result"
      modelFingerprint: "215C6D4AFC6B5001AC9D2FA01D518C77"
      index: 5
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "ENUM"
        content: !<regular>
          value: "PRESENT"
        valueType: "org.springframework.boot.context.properties.source.ConfigurationPropertyState"
        uuid: "Enum-org.springframework.boot.context.properties.source.ConfigurationPropertyState-PRESENT"
        fixed: true
        equalsMethodPresent: true
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    uuid: "06fff9e8-aab3-3323-9bf4-83f0394f49b3"
    deleted: false
    disabled: true
    ignoredBySystem: false
    failureReason:
      reason: "METHOD_WITHOUT_EXPRESSION_SUPPORT"
      details: "Expression missing: java.lang.Iterable.iterator() : java.util.Iterator"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: true
  - pathId: "path2"
    pathIdForUser: "path2"
    testPathName: "searchWhenPredicateNotTestItem"
    nameDefinedByUser: false
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "B490CFEF47F564CE64BC46F8CD4F9DEF"
    problemWasSolvedByProver: false
    truncated: false
    inputParameters:
    - type: "INPUT"
      name: "source"
      modelFingerprint: "5BFEDCB7460AC592DAB3A8DD97CED8A8"
      index: 1
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        valueType: "java.lang.Iterable"
        uuid: "search_iterable1"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "INPUT"
      name: "predicate"
      modelFingerprint: "5AB160B1932BFCC24800D287A98C368D"
      index: 2
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        valueType: "java.util.function.Predicate"
        uuid: "search_predicate1"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "Assert"
      modelFingerprint: "D66D5F9FFE63C8E4B829FE6D193CE6E1"
      index: 3
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        valueType: "org.springframework.util.Assert"
        uuid: "org.springframework.util.Assert"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "org.springframework.util.Assert"
        name: "notNull"
        parameters:
        - name: "object"
          value:
            sapientType: "MOCK"
            valueType: "java.lang.Iterable"
            uuid: "search_iterable1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "message"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "Source must not be null"
            valueType: "java.lang.String"
            fixed: true
            equalsMethodPresent: false
            explicitCastNeeded: false
        signature: "notNull(Iterable,String): void"
        returnValue:
          sapientType: "VOID"
          valueType: "void"
          uuid: "search_void1"
          fixed: true
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "Assert"
      modelFingerprint: "55779EEE47C46E4306B2E65D8107E32A"
      index: 4
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        valueType: "org.springframework.util.Assert"
        uuid: "org.springframework.util.Assert"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "org.springframework.util.Assert"
        name: "notNull"
        parameters:
        - name: "object"
          value:
            sapientType: "MOCK"
            valueType: "java.util.function.Predicate"
            uuid: "search_predicate1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "message"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "Predicate must not be null"
            valueType: "java.lang.String"
            fixed: true
            equalsMethodPresent: false
            explicitCastNeeded: false
        signature: "notNull(Predicate,String): void"
        returnValue:
          sapientType: "VOID"
          valueType: "void"
          uuid: "search_void2"
          fixed: true
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "RESULT"
      name: "result"
      modelFingerprint: "75431720ECDEA53E347CAC6A8C13518F"
      index: 5
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "ENUM"
        content: !<regular>
          value: "ABSENT"
        valueType: "org.springframework.boot.context.properties.source.ConfigurationPropertyState"
        uuid: "Enum-org.springframework.boot.context.properties.source.ConfigurationPropertyState-ABSENT"
        fixed: true
        equalsMethodPresent: true
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    uuid: "f328f7bb-da87-3b6f-9463-4aa7094b1003"
    deleted: false
    disabled: true
    ignoredBySystem: false
    failureReason:
      reason: "METHOD_WITHOUT_EXPRESSION_SUPPORT"
      details: "Expression missing: java.lang.Iterable.iterator() : java.util.Iterator"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: true
