---
modelFingerprint: "8C648A6FAA611D9D8B0D6D9520E27B45"
methods:
- method:
    name: "isUsingSources"
    returnType: "boolean"
    signature: "isUsingSources(java.lang.Iterable<org.springframework.core.env.PropertySource<?>>)\
      \ : boolean"
    instructionFingerprint: "0561389946EDF54148C7B05BBB18A9DC"
    parametersTypes:
    - "java.lang.Iterable"
  paths:
  - pathId: "path1"
    pathIdForUser: "path1"
    testPathName: "isUsingSourcesWhenThisSourcesEqualsSources"
    nameDefinedByUser: false
    constructorSignature: "<init>(java.lang.Iterable<org.springframework.core.env.PropertySource<?>>)\
      \ : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "F4963A76F95E7D7BD04A42DA986FF1C6"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "33ACDF95B06151FB8F8F3B644D2AE455"
      index: 1
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "OBJECT"
        content: !<new>
          target: "org.springframework.boot.context.properties.source.SpringConfigurationPropertySources"
          parameters:
          - name: "sources"
            value:
              sapientType: "MOCK"
              valueType: "java.lang.Iterable"
              uuid: "<init>_iterable1"
              fixed: false
              equalsMethodPresent: false
              explicitCastNeeded: false
          privateConstructor: false
          createdByTargetCode: false
        suggestedContent: !<new>
          target: "org.springframework.boot.context.properties.source.SpringConfigurationPropertySources"
          parameters:
          - name: "sources"
            value:
              sapientType: "UNKNOWN"
              valueType: "java.lang.Iterable"
              genericValueType: "org.springframework.core.env.PropertySource<?>"
              uuid: "<init>_iterable1"
              fixed: false
              equalsMethodPresent: false
              explicitCastNeeded: false
          privateConstructor: false
          createdByTargetCode: false
        valueType: "org.springframework.boot.context.properties.source.SpringConfigurationPropertySources"
        uuid: "target"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "INPUT"
      name: "sources"
      modelFingerprint: "00180D49DAE62E31AD93A0BD5B35B6EF"
      index: 2
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        valueType: "java.lang.Iterable"
        uuid: "<init>_iterable1"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "Assert"
      modelFingerprint: "19AFE954898953292D622B023222DF21"
      index: 3
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        valueType: "org.springframework.util.Assert"
        uuid: "org.springframework.util.Assert"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "org.springframework.util.Assert"
        name: "notNull"
        parameters:
        - name: "object"
          value:
            sapientType: "MOCK"
            valueType: "java.lang.Iterable"
            uuid: "<init>_iterable1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "message"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "Sources must not be null"
            valueType: "java.lang.String"
            fixed: true
            equalsMethodPresent: false
            explicitCastNeeded: false
        signature: "notNull(Iterable,String): void"
        returnValue:
          sapientType: "VOID"
          valueType: "void"
          uuid: "<init>_void1"
          fixed: true
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "RESULT"
      name: "result"
      modelFingerprint: "753659628F1B3F179A2EF0629F555437"
      index: 4
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "BASIC"
        content: !<regular>
          value: true
        valueType: "boolean"
        fixed: true
        equalsMethodPresent: true
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    uuid: "4f7f2e04-5085-3c77-9c5c-510e42b3bd0f"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
  - pathId: "path2"
    pathIdForUser: "path2"
    testPathName: "isUsingSourcesWhenThisSourcesNotEqualsSources"
    nameDefinedByUser: false
    constructorSignature: "<init>(java.lang.Iterable<org.springframework.core.env.PropertySource<?>>)\
      \ : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "00E59E00C09799F92E2D3D9CB0D0AC59"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "33ACDF95B06151FB8F8F3B644D2AE455"
      index: 1
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "OBJECT"
        content: !<new>
          target: "org.springframework.boot.context.properties.source.SpringConfigurationPropertySources"
          parameters:
          - name: "sources"
            value:
              sapientType: "MOCK"
              valueType: "java.lang.Iterable"
              uuid: "<init>_iterable1"
              fixed: false
              equalsMethodPresent: false
              explicitCastNeeded: false
          privateConstructor: false
          createdByTargetCode: false
        suggestedContent: !<new>
          target: "org.springframework.boot.context.properties.source.SpringConfigurationPropertySources"
          parameters:
          - name: "sources"
            value:
              sapientType: "UNKNOWN"
              valueType: "java.lang.Iterable"
              genericValueType: "org.springframework.core.env.PropertySource<?>"
              uuid: "<init>_iterable1"
              fixed: false
              equalsMethodPresent: false
              explicitCastNeeded: false
          privateConstructor: false
          createdByTargetCode: false
        valueType: "org.springframework.boot.context.properties.source.SpringConfigurationPropertySources"
        uuid: "target"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "INPUT"
      name: "sources"
      modelFingerprint: "00180D49DAE62E31AD93A0BD5B35B6EF"
      index: 2
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        valueType: "java.lang.Iterable"
        uuid: "isUsingSources_iterable1"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "Assert"
      modelFingerprint: "19AFE954898953292D622B023222DF21"
      index: 3
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        valueType: "org.springframework.util.Assert"
        uuid: "org.springframework.util.Assert"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "org.springframework.util.Assert"
        name: "notNull"
        parameters:
        - name: "object"
          value:
            sapientType: "MOCK"
            valueType: "java.lang.Iterable"
            uuid: "<init>_iterable1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "message"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "Sources must not be null"
            valueType: "java.lang.String"
            fixed: true
            equalsMethodPresent: false
            explicitCastNeeded: false
        signature: "notNull(Iterable,String): void"
        returnValue:
          sapientType: "VOID"
          valueType: "void"
          uuid: "<init>_void1"
          fixed: true
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "RESULT"
      name: "result"
      modelFingerprint: "3A21543F56248AC92654D6E439128AED"
      index: 4
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "BASIC"
        content: !<regular>
          value: false
        valueType: "boolean"
        fixed: true
        equalsMethodPresent: true
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    uuid: "9cb242de-be1f-37eb-b291-8765c225da25"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
- method:
    name: "iterator"
    returnType: "java.util.Iterator"
    signature: "iterator() : java.util.Iterator<org.springframework.boot.context.properties.source.ConfigurationPropertySource>"
    instructionFingerprint: "CBF4850B6BCA87D3580BBF0DE20041F4"
    parametersTypes: []
  paths:
  - pathId: "path1"
    pathIdForUser: "path1"
    testPathName: "iteratorTest"
    nameDefinedByUser: false
    constructorSignature: "<init>(java.lang.Iterable<org.springframework.core.env.PropertySource<?>>)\
      \ : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "5FA05DB48EC65CD016DFE0BF64D09B81"
    problemWasSolvedByProver: false
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "33ACDF95B06151FB8F8F3B644D2AE455"
      index: 1
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "OBJECT"
        content: !<new>
          target: "org.springframework.boot.context.properties.source.SpringConfigurationPropertySources"
          parameters:
          - name: "sources"
            value:
              sapientType: "MOCK"
              valueType: "java.lang.Iterable"
              uuid: "<init>_iterable1"
              fixed: false
              equalsMethodPresent: false
              explicitCastNeeded: false
          privateConstructor: false
          createdByTargetCode: false
        suggestedContent: !<new>
          target: "org.springframework.boot.context.properties.source.SpringConfigurationPropertySources"
          parameters:
          - name: "sources"
            value:
              sapientType: "UNKNOWN"
              valueType: "java.lang.Iterable"
              genericValueType: "org.springframework.core.env.PropertySource<?>"
              uuid: "<init>_iterable1"
              fixed: false
              equalsMethodPresent: false
              explicitCastNeeded: false
          privateConstructor: false
          createdByTargetCode: false
        valueType: "org.springframework.boot.context.properties.source.SpringConfigurationPropertySources"
        uuid: "target"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "Assert"
      modelFingerprint: "19AFE954898953292D622B023222DF21"
      index: 2
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        valueType: "org.springframework.util.Assert"
        uuid: "org.springframework.util.Assert"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "org.springframework.util.Assert"
        name: "notNull"
        parameters:
        - name: "object"
          value:
            sapientType: "MOCK"
            valueType: "java.lang.Iterable"
            uuid: "<init>_iterable1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "message"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "Sources must not be null"
            valueType: "java.lang.String"
            fixed: true
            equalsMethodPresent: false
            explicitCastNeeded: false
        signature: "notNull(Iterable,String): void"
        returnValue:
          sapientType: "VOID"
          valueType: "void"
          uuid: "<init>_void1"
          fixed: true
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "RESULT"
      name: "result"
      modelFingerprint: "D3FDA91A1373CE77D4FEC0FC2FE3683E"
      index: 3
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "NOT_NULL"
        valueType: "java.util.Iterator"
        genericValueType: "org.springframework.boot.context.properties.source.ConfigurationPropertySource"
        uuid: "iterator_springConfigurationPropertySources.SourcesIterator1"
        fixed: true
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    uuid: "78c09fb6-edcf-3ce7-9932-6ef4ffc152b3"
    deleted: false
    disabled: true
    ignoredBySystem: false
    failureReason:
      reason: "METHOD_WITHOUT_EXPRESSION_SUPPORT"
      details: "Expression missing: java.lang.Iterable.iterator() : java.util.Iterator"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: true
